### ISSUE TITLE
epoll_ctl: No such file or directory

### ISSUE THREAD

**Issue by betachen** [swirlycloud/swirlyc#55]
when i switched from "select" to "epoll" in mongoose.c ：
line 52: #define MG_MGR_EV_MGR 1

compile done.
run server " swirlyd -n"
get any URI then report a error as : "epoll_ctl: No such file or directory"
then i debug step in, i found that maybe u forget initializing epoll_fd or fd in cpp code.

by the way, i found that mongoose updated to version 6.3, is that necessary to update for swirly?
i have compiled well, but i don't know if there is any bug in code.

**Comment by marayl** [comment]
Sorry for not replying sooner. I will take a look at this issue in the coming days.
Regards,
Mark

**Comment by marayl** [comment]
This issue was caused by a bug in Mongoose. I will raise a Mongoose Pull Request to push the fix upstream.

**Comment by marayl** [comment]
https://github.com/cesanta/mongoose/pull/637
