### ISSUE TITLE
what does it mean on "view"?

### ISSUE THREAD

**Issue by betachen** [swirlycloud/swirlyc#66]
is that put two way to explain "view" better?
I adjust that put "myview" and "view" in URI.
view for public, such as depth/ticker/trades for specific market.
my view for private data in "sess".

Or some definition i didn't find? please help me. thanks

**Comment by marayl** [comment]
Hi. If I understand your question correctly, then you're asking why there are two "view" URLs? If so, then a little insight is available on the following page:

http://www.swirlycloud.com/RestApi.html

The api/sess/view URL allows users that are logged-in to fetch Order, Trade, Posn and View updates in a single HTTP request. The api/view URL, on the other hand, does not require a login. (View data is considered public information.) Both URLs currently return the same view of the Order-Book.

If this explanation is insufficient or I have misunderstood, then please let me know.

**Comment by betachen** [comment]
Sorry for my poor English.
Sure, I have got the means that you explain and RestApi.html.
there is the question:
1. Is that "view" for tikcer/depth/latest trades in a market?
2. why not use "myview" for session which is different from "view" for public, will it be confused for client users, even get the same view of the order-book?
will "myview" be publish-subscribe mode, if someone want to subscribe for personal with personal-filter, not all market data.
I mean does it got more some difference between public-"view" and seesion-"view" in future?

**Comment by marayl** [comment]
Your English is fine! These are good questions. I will endeavor to respond in full within the next 48 hours.

**Comment by marayl** [comment]
I have updated the following pages:

- http://www.swirlycloud.com/RestApi.html
- http://www.swirlycloud.com/MarketData.html

Please let me know if these updates answer your questions.

**Comment by betachen** [comment]
oh,thanks.
i have read more details with  new RestApi.html and MarketData.html.
it's useful for me.
thanks a lot.
